project_name: go-passbolt-cli
checksum:
  name_template: 'checksums.txt'
builds:
  - env: [CGO_ENABLED=0]
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: passbolt
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - completion/*
      - man/*
    format_overrides:
      - goos: windows
        format: zip
release:
  draft: true
  header: |
    ## Release {{ .Tag }} - ({{ .Date }})
nfpms:
- maintainer: Samuel Lorch <sam@lorch.net>
  description: A CLI for Passbolt.
  homepage: https://github.com/passbolt/go-passbolt-cli
  license: MIT
  contents:
    - src: /home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/bash
      dst: /usr/share/bash-completion/completions/passbolt
    - src: /home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/zsh
      dst: /usr/share/zsh/site-functions/_passbolt
    - src: /home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/fish
      dst: /usr/share/fish/vendor_completions.d/passbolt.fish
    - src: /home/runner/work/go-passbolt-cli/go-passbolt-cli/man/*
      dst: /usr/share/man/man1/
  recommends:
    - bash_completion
  formats:
    - deb
    - rpm