project_name: go-passbolt-cli
checksum:
  name_template: 'checksums.txt'
builds:
  - env: [CGO_ENABLED=0]
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: passbolt
archives:
  - files:
      - completion/*
      - man/*
    format_overrides:
      - goos: windows
        format: zip
release:
  draft: true
  header: |
    ## Release {{ .Tag }} - ({{ .Date }})
nfpms:
- maintainer: Samuel Lorch <sam@soontm.de>
  description: A CLI for Passbolt.
  homepage: https://github.com/passbolt/go-passbolt-cli
  license: MIT
  contents:
    - src: /home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/bash
      dst: /usr/share/bash-completion/completions/passbolt
    - src: /home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/zsh
      dst: /usr/share/zsh/site-functions/_passbolt
    - src: /home/runner/work/go-passbolt-cli/go-passbolt-cli/completion/fish
      dst: /usr/share/fish/vendor_completions.d/passbolt.fish
    - src: /home/runner/work/go-passbolt-cli/go-passbolt-cli/man/*
      dst: /usr/share/man/man1/
  recommends:
    - bash_completion
  formats:
    - deb
    - rpm
brews:
  - homepage: https://github.com/passbolt/go-passbolt-cli
    license: "MIT"
    skip_upload: false
    description: "A CLI tool to interact with Passbolt, a Open source Password Manager for Teams"
    folder: Formula
    install: |
      bin.install "passbolt"
      bash_completion.install "completion/bash" => "passbolt"
      zsh_completion.install "completion/zsh" => "_passbolt"
      fish_completion.install "completion/fish" => "passbolt.fish"
      man1.install Dir["man/*"]
      # ...
    repository:
      owner: passbolt
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
        

