name: goreleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Tests
        run: go test -v ./...

      - name: Run go vet
        run: go vet ./...

  goreleaser:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Generate Man and Completions
        run: |
          mkdir completion
          go run *.go completion bash > completion/bash
          go run *.go completion zsh > completion/zsh
          go run *.go completion fish > completion/fish
          go run *.go completion powershell > completion/powershell
          mkdir man
          go run *.go gendoc --type man

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Build
        run: dist/go-passbolt-cli_linux_amd64_v1/passbolt -v

      - uses: actions/upload-artifact@v4
        with:
          name: go-passbolt-cli-artifacts
          path: dist/
